version: '3.5'
services:
  site:
    command: jekyll serve --incremental
    environment:
      - FORCE_POLLING=true
    image: jekyll/jekyll:latest@sha256:15fa79ee6293d7970fe2456fa64ea64bbaf308617b2841e73d9e58cfe09445b6
    volumes:
      - ..:/srv/jekyll
      - ../vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      - 80:4000
