version: '3.5'
services:
  site:
    command: jekyll serve --incremental
    environment:
      - FORCE_POLLING=true
    image: jekyll/jekyll:latest@sha256:20909574b8f15b1e02f82e91c16eeeab14c9379bb96f26f72ad5f142ec5df396
    volumes:
      - ..:/srv/jekyll
      - ../vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      - 80:4000
