version: '3.5'
services:
  site:
    command: jekyll serve --incremental
    environment:
      - FORCE_POLLING=true
    image: jekyll/jekyll:latest@sha256:f0ccb9842a530181f73fe2b126a01634810a52ec6667c4b804d9d09432eadf4a
    volumes:
      - ..:/srv/jekyll
      - ../vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      - 80:4000
